# Generated by Django 2.2.17 on 2020-11-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='gjgjgjg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='kkjhkhk',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
